package depuradordhcp;

/**
 *
 * @author Carlos Rincon
 */
public class Queries {
    public static String CONSULTAR_MAC_REGISTROS_REPETIDOS_DHCP_MTA = "SELECT MTA_MAC, COUNT(*) AS CUENTA FROM DHCP_MTA GROUP BY MTA_MAC";
    public static String CONSULTAR_MAC_REGISTROS_REPETIDOS_DHCP_CABLE_MODEMS = "SELECT CAMO_MAC, COUNT(*) AS CUENTA FROM DHCP_CABLE_MODEMS GROUP BY CAMO_MAC";
    public static String CONSULTAR_MAC_REGISTROS_REPETIDOS_DHCP_CPE = "SELECT CPE_MAC, COUNT(*) AS CUENTA FROM DHCP_CPE GROUP BY CPE_MAC";
    public static String CONSULTAR_MAC_REGISTROS_REPETIDOS_DHCP_FQDN = "SELECT FQDN_MAC, COUNT(*) AS CUENTA FROM DHCP_FQDN GROUP BY FQDN_MAC";
    
    
    public static String CONSULTAR_ID_REGISTROS_REPETIDOS_DHCP_MTA = "SELECT ID_DHCP_MTA FROM DHCP_MTA WHERE MTA_MAC = ?";
    public static String CONSULTAR_ID_REGISTROS_REPETIDOS_DHCP_CABLE_MODEMS = "SELECT ID_DHCP_CABLE_MODEMS FROM DHCP_CABLE_MODEMS WHERE CAMO_MAC = ?";
    public static String CONSULTAR_ID_REGISTROS_REPETIDOS_DHCP_CPE = "SELECT ID_DHCP_CPE FROM DHCP_CPE WHERE CPE_MAC = ?";
    public static String CONSULTAR_ID_REGISTROS_REPETIDOS_DHCP_FQDN = "SELECT ID_DHCP_FQDN FROM DHCP_FQDN WHERE FQDN_MAC = ?";
    
    public static String BORRAR_REGISTRO_POR_MAC_MTA = "DELETE FROM DHCP_MTA WHERE ID_DHCP_MTA = ?";
    public static String BORRAR_REGISTRO_POR_MAC_CM = "DELETE FROM DHCP_CABLE_MODEMS WHERE ID_DHCP_CABLE_MODEMS = ?";
    public static String BORRAR_REGISTRO_POR_MAC_CPE = "DELETE FROM DHCP_CPE WHERE ID_DHCP_CPE = ?";
    public static String BORRAR_REGISTRO_POR_MAC_FQDN = "DELETE FROM DHCP_FQDN WHERE ID_DHCP_FQDN = ?";
    
}
